export interface SeedLead {
  companyName: string;
  website: string;
  industry: string;
  location: string;
  revenue: number | null;
  employees: number | null;
  foundedYear: number | null;
  description: string;
  revenueGrowthPercent: number | null;
  employeeGrowthPercent: number | null;
  contact: {
    name: string;
    title: string;
    email: string;
    linkedin?: string;
  };
}

export const defaultICP = {
  name: 'B2B SaaS Mid-Market Acquisition',
  industries: ['SaaS / Software', 'Cloud Infrastructure', 'Cybersecurity', 'Fintech'],
  minRevenue: 1000000,
  maxRevenue: 10000000,
  minEmployees: 10,
  maxEmployees: 100,
  locations: ['United States', 'Canada'],
  isActive: true,
};

export const sampleLeads: SeedLead[] = [
  {
    companyName: 'Apex Cloud Solutions',
    website: 'https://apexcloud.example.com',
    industry: 'SaaS / Software',
    location: 'Austin, TX, United States',
    revenue: 4500000,
    employees: 38,
    foundedYear: 2018,
    description: 'Enterprise workflow automation for logistics and supply chain operators.',
    revenueGrowthPercent: 32,
    employeeGrowthPercent: 24,
    contact: {
      name: 'Marcus Vance',
      title: 'Founder & CEO',
      email: 'marcus@apexcloud.example.com',
      linkedin: 'https://linkedin.com/in/marcus-vance-apex',
    },
  },
  {
    companyName: 'Sentient Security Labs',
    website: 'https://sentientsec.example.com',
    industry: 'Cybersecurity',
    location: 'Boston, MA, United States',
    revenue: 6200000,
    employees: 52,
    foundedYear: 2017,
    description: 'Next-gen vulnerability management and threat vector modeling for regional banks.',
    revenueGrowthPercent: 41,
    employeeGrowthPercent: 30,
    contact: {
      name: 'Dr. Elena Rostova',
      title: 'Co-Founder & CTO',
      email: 'elena@sentientsec.example.com',
      linkedin: 'https://linkedin.com/in/elena-rostova-sec',
    },
  },
  {
    companyName: 'ClearPay Logistics',
    website: 'https://clearpaylogistics.example.com',
    industry: 'Fintech',
    location: 'Toronto, ON, Canada',
    revenue: 3800000,
    employees: 29,
    foundedYear: 2019,
    description: 'B2B cross-border freight payment orchestration and escrow services.',
    revenueGrowthPercent: 38,
    employeeGrowthPercent: 20,
    contact: {
      name: 'Julian Tremblay',
      title: 'Managing Director',
      email: 'julian@clearpaylogistics.example.com',
      linkedin: 'https://linkedin.com/in/julian-tremblay-cp',
    },
  },
  {
    companyName: 'DataMesh Orchestration',
    website: 'https://datamesh-iq.example.com',
    industry: 'Cloud Infrastructure',
    location: 'Denver, CO, United States',
    revenue: 8100000,
    employees: 64,
    foundedYear: 2016,
    description: 'Real-time telemetry and data pipeline optimization for distributed microservices.',
    revenueGrowthPercent: 25,
    employeeGrowthPercent: 15,
    contact: {
      name: 'Rachel Wei',
      title: 'CEO',
      email: 'rachel@datamesh-iq.example.com',
      linkedin: 'https://linkedin.com/in/rachel-wei-datamesh',
    },
  },
  {
    companyName: 'OmniDesk CRM',
    website: 'https://omnidesk-app.example.com',
    industry: 'SaaS / Software',
    location: 'Chicago, IL, United States',
    revenue: 2900000,
    employees: 24,
    foundedYear: 2020,
    description: 'Vertical customer relationship platform specifically designed for commercial roofing contractors.',
    revenueGrowthPercent: 45,
    employeeGrowthPercent: 35,
    contact: {
      name: 'Tyler Brooks',
      title: 'Founder & CEO',
      email: 'tyler@omnidesk-app.example.com',
      linkedin: 'https://linkedin.com/in/tyler-brooks-omni',
    },
  },
  {
    companyName: 'StrataHealth Tech',
    website: 'https://stratahealth.example.com',
    industry: 'Healthcare IT',
    location: 'Nashville, TN, United States',
    revenue: 5500000,
    employees: 45,
    foundedYear: 2015,
    description: 'HIPAA-compliant patient communications and appointment management software.',
    revenueGrowthPercent: 18,
    employeeGrowthPercent: 12,
    contact: {
      name: 'Karen Lindqvist',
      title: 'President & CEO',
      email: 'karen@stratahealth.example.com',
      linkedin: 'https://linkedin.com/in/karen-lindqvist-health',
    },
  },
  {
    companyName: 'Beacon Compliance AI',
    website: 'https://beaconcompliance.example.com',
    industry: 'SaaS / Software',
    location: 'New York, NY, United States',
    revenue: 7400000,
    employees: 58,
    foundedYear: 2018,
    description: 'Automated SOC2 and ISO27001 evidence collection for growing fintech companies.',
    revenueGrowthPercent: 35,
    employeeGrowthPercent: 22,
    contact: {
      name: 'Devon Mercer',
      title: 'Co-Founder & CEO',
      email: 'devon@beaconcompliance.example.com',
      linkedin: 'https://linkedin.com/in/devon-mercer-beacon',
    },
  },
  {
    companyName: 'Kestrel Analytics',
    website: 'https://kestrelanalytics.example.com',
    industry: 'Cloud Infrastructure',
    location: 'Seattle, WA, United States',
    revenue: 1900000,
    employees: 16,
    foundedYear: 2021,
    description: 'Kubernetes cloud-cost observability and automatic pod rightsizing.',
    revenueGrowthPercent: 60,
    employeeGrowthPercent: 45,
    contact: {
      name: 'Amara Okafor',
      title: 'Founder & CEO',
      email: 'amara@kestrelanalytics.example.com',
      linkedin: 'https://linkedin.com/in/amara-okafor-kestrel',
    },
  },
  {
    companyName: 'Veloce Commerce',
    website: 'https://velocecommerce.example.com',
    industry: 'E-commerce Platforms',
    location: 'Montreal, QC, Canada',
    revenue: 4100000,
    employees: 32,
    foundedYear: 2018,
    description: 'Headless storefront engine for luxury direct-to-consumer apparel brands.',
    revenueGrowthPercent: 22,
    employeeGrowthPercent: 10,
    contact: {
      name: 'Mathieu Roy',
      title: 'Co-Founder & COO',
      email: 'mathieu@velocecommerce.example.com',
      linkedin: 'https://linkedin.com/in/mathieu-roy-veloce',
    },
  },
  {
    companyName: 'Quorum Billing',
    website: 'https://quorumbilling.example.com',
    industry: 'Fintech',
    location: 'San Francisco, CA, United States',
    revenue: 9300000,
    employees: 78,
    foundedYear: 2016,
    description: 'Usage-based metering and billing infrastructure for developer-first SaaS products.',
    revenueGrowthPercent: 28,
    employeeGrowthPercent: 19,
    contact: {
      name: 'Simon Patel',
      title: 'CEO',
      email: 'simon@quorumbilling.example.com',
      linkedin: 'https://linkedin.com/in/simon-patel-quorum',
    },
  },
  {
    companyName: 'Vanguard Cyber Defense',
    website: 'https://vanguardcyber.example.com',
    industry: 'Cybersecurity',
    location: 'Vancouver, BC, Canada',
    revenue: 3200000,
    employees: 25,
    foundedYear: 2019,
    description: 'Managed detection and response tailored for regional credit unions and accounting firms.',
    revenueGrowthPercent: 30,
    employeeGrowthPercent: 15,
    contact: {
      name: 'Chloe Zhang',
      title: 'CEO & Founder',
      email: 'chloe@vanguardcyber.example.com',
      linkedin: 'https://linkedin.com/in/chloe-zhang-vanguard',
    },
  },
  {
    companyName: 'Nordic Wave Media',
    website: 'https://nordicwave.example.com',
    industry: 'Digital Media & Agency',
    location: 'Minneapolis, MN, United States',
    revenue: 1200000,
    employees: 14,
    foundedYear: 2017,
    description: 'Performance digital advertising agency and podcast production house.',
    revenueGrowthPercent: 8,
    employeeGrowthPercent: 5,
    contact: {
      name: 'Lars Halvorsen',
      title: 'Owner',
      email: 'lars@nordicwave.example.com',
    },
  },
  {
    companyName: 'PulsePulse HR',
    website: 'https://pulsepulsehr.example.com',
    industry: 'SaaS / Software',
    location: 'Atlanta, GA, United States',
    revenue: 1500000,
    employees: 12,
    foundedYear: 2021,
    description: 'Employee sentiment polling and micro-feedback platform for remote-first agencies.',
    revenueGrowthPercent: 50,
    employeeGrowthPercent: 40,
    contact: {
      name: 'Brianna Jackson',
      title: 'CEO',
      email: 'brianna@pulsepulsehr.example.com',
      linkedin: 'https://linkedin.com/in/brianna-jackson-pulse',
    },
  },
  {
    companyName: 'Silverline Hardware Solutions',
    website: 'https://silverlinehardware.example.com',
    industry: 'Industrial Equipment',
    location: 'Cleveland, OH, United States',
    revenue: 14500000,
    employees: 140,
    foundedYear: 2004,
    description: 'Wholesale distributor of precision mechanical fasteners and warehouse fixtures.',
    revenueGrowthPercent: 4,
    employeeGrowthPercent: 2,
    contact: {
      name: 'Arthur Miller',
      title: 'President',
      email: 'amiller@silverlinehardware.example.com',
    },
  },
  {
    companyName: 'Terraform IoT',
    website: 'https://terraform-iot.example.com',
    industry: 'Hardware & IoT',
    location: 'Phoenix, AZ, United States',
    revenue: 800000,
    employees: 9,
    foundedYear: 2022,
    description: 'Soil moisture telemetry sensors and solar telemetry nodes for commercial citrus growers.',
    revenueGrowthPercent: 12,
    employeeGrowthPercent: 0,
    contact: {
      name: 'Diego Gutierrez',
      title: 'Founder',
      email: 'diego@terraform-iot.example.com',
    },
  },
  {
    companyName: 'Logos EdTech',
    website: 'https://logosedtech.example.com',
    industry: 'EdTech',
    location: 'San Diego, CA, United States',
    revenue: 2600000,
    employees: 21,
    foundedYear: 2019,
    description: 'Gamified language acquisition curriculum for K-12 private academies.',
    revenueGrowthPercent: 15,
    employeeGrowthPercent: 10,
    contact: {
      name: 'Hannah Abbott',
      title: 'Executive Director',
      email: 'hannah@logosedtech.example.com',
      linkedin: 'https://linkedin.com/in/hannah-abbott-logos',
    },
  },
  {
    companyName: 'Zenith Freight Network',
    website: 'https://zenithfreight.example.com',
    industry: 'Transportation & Logistics',
    location: 'Dallas, TX, United States',
    revenue: 22000000,
    employees: 185,
    foundedYear: 2011,
    description: 'Regional asset-backed flatbed carrier network serving oilfield machinery manufacturers.',
    revenueGrowthPercent: 6,
    employeeGrowthPercent: 4,
    contact: {
      name: 'Travis Calhoun',
      title: 'COO',
      email: 'tcalhoun@zenithfreight.example.com',
    },
  },
  {
    companyName: 'Acuity Financial Advisory',
    website: 'https://acuityfinadvisory.example.com',
    industry: 'Accounting & Professional Services',
    location: 'Philadelphia, PA, United States',
    revenue: 3400000,
    employees: 22,
    foundedYear: 2013,
    description: 'Retained outsourced CFO and bookkeeping services for Series A tech startups.',
    revenueGrowthPercent: 9,
    employeeGrowthPercent: 5,
    contact: {
      name: 'Patricia Hughes',
      title: 'Managing Partner',
      email: 'patricia@acuityfinadvisory.example.com',
    },
  },
  {
    companyName: 'Synthetix Data Engine',
    website: 'https://synthetixdata.example.com',
    industry: 'SaaS / Software',
    location: 'Salt Lake City, UT, United States',
    revenue: 5100000,
    employees: 41,
    foundedYear: 2019,
    description: 'Synthetic test data generation engine for autonomous robotics and computer vision pipelines.',
    revenueGrowthPercent: 48,
    employeeGrowthPercent: 32,
    contact: {
      name: 'Karthik Raman',
      title: 'Founder & CEO',
      email: 'karthik@synthetixdata.example.com',
      linkedin: 'https://linkedin.com/in/karthik-raman-data',
    },
  },
  {
    companyName: 'Harbor Light Care',
    website: 'https://harborlightcare.example.com',
    industry: 'Home Healthcare Services',
    location: 'Tampa, FL, United States',
    revenue: 6800000,
    employees: 85,
    foundedYear: 2014,
    description: 'In-home non-medical senior companionship and hospice aid staffing agency.',
    revenueGrowthPercent: 7,
    employeeGrowthPercent: 5,
    contact: {
      name: 'Bernadette Shaw',
      title: 'Director',
      email: 'bshaw@harborlightcare.example.com',
    },
  },
  {
    companyName: 'Proxima Identity',
    website: 'https://proximaidentity.example.com',
    industry: 'Cybersecurity',
    location: 'Calgary, AB, Canada',
    revenue: 4700000,
    employees: 36,
    foundedYear: 2018,
    description: 'Passwordless biometrics-backed IAM for municipal utilities and smart city grids.',
    revenueGrowthPercent: 33,
    employeeGrowthPercent: 20,
    contact: {
      name: 'Nolan Ferguson',
      title: 'CEO',
      email: 'nolan@proximaidentity.example.com',
      linkedin: 'https://linkedin.com/in/nolan-ferguson-iam',
    },
  },
  {
    companyName: 'Bespoke Artisan Roast',
    website: 'https://bespokeroast.example.com',
    industry: 'Food & Beverage',
    location: 'Portland, OR, United States',
    revenue: 1100000,
    employees: 18,
    foundedYear: 2016,
    description: 'Direct-trade specialty micro-roaster with local retail cafe operations.',
    revenueGrowthPercent: 3,
    employeeGrowthPercent: 0,
    contact: {
      name: 'Eliot Moss',
      title: 'Head Roaster & Owner',
      email: 'eliot@bespokeroast.example.com',
    },
  },
  {
    companyName: 'CoreStack DevOps',
    website: 'https://corestack-devops.example.com',
    industry: 'Cloud Infrastructure',
    location: 'Ottawa, ON, Canada',
    revenue: 3900000,
    employees: 27,
    foundedYear: 2020,
    description: 'Internal developer platform (IDP) templates with automated GitOps policy enforcement.',
    revenueGrowthPercent: 44,
    employeeGrowthPercent: 28,
    contact: {
      name: 'Sophie Dubois',
      title: 'Co-Founder & CEO',
      email: 'sophie@corestack-devops.example.com',
      linkedin: 'https://linkedin.com/in/sophie-dubois-devops',
    },
  },
  {
    companyName: 'Evergreen Environmental Consulting',
    website: 'https://evergreenenv.example.com',
    industry: 'Environmental Services',
    location: 'Boise, ID, United States',
    revenue: 2800000,
    employees: 23,
    foundedYear: 2012,
    description: 'Phase I and II environmental site assessments and wetland mitigation permitting.',
    revenueGrowthPercent: 5,
    employeeGrowthPercent: 2,
    contact: {
      name: 'Craig Sterling',
      title: 'Principal Geologist',
      email: 'csterling@evergreenenv.example.com',
    },
  },
  {
    companyName: 'LumenIQ Knowledge Graph',
    website: 'https://lumeniq.example.com',
    industry: 'SaaS / Software',
    location: 'Raleigh, NC, United States',
    revenue: null, // intentionally missing to demonstrate incomplete data handling
    employees: 22,
    foundedYear: 2020,
    description: 'Enterprise search and internal ontology construction engine for pharmaceutical R&D.',
    revenueGrowthPercent: null,
    employeeGrowthPercent: 30,
    contact: {
      name: 'Deepak Nair',
      title: 'Founder',
      email: 'deepak@lumeniq.example.com',
      linkedin: 'https://linkedin.com/in/deepak-nair-lumen',
    },
  },
  {
    companyName: 'Veritas Legal Intake',
    website: 'https://veritaslegalintake.example.com',
    industry: 'LegalTech',
    location: 'Houston, TX, United States',
    revenue: 3100000,
    employees: null, // intentionally missing
    foundedYear: 2017,
    description: 'AI chatbot and bilingual phone intake CRM for mass tort and personal injury firms.',
    revenueGrowthPercent: 22,
    employeeGrowthPercent: null,
    contact: {
      name: 'Maria Elena Garza',
      title: 'Managing Director',
      email: 'maria@veritaslegalintake.example.com',
    },
  },
  {
    companyName: 'Apex Precision Machining',
    website: 'https://apexprecision.example.com',
    industry: 'Manufacturing',
    location: 'Milwaukee, WI, United States',
    revenue: 18500000,
    employees: 120,
    foundedYear: 1998,
    description: 'CNC 5-axis milling of titanium and Inconel components for aerospace landing gear.',
    revenueGrowthPercent: 2,
    employeeGrowthPercent: -1,
    contact: {
      name: 'George Kowalski',
      title: 'CEO',
      email: 'gkowalski@apexprecision.example.com',
    },
  },
  {
    companyName: 'Aura Energy Intelligence',
    website: 'https://auraenergy.example.com',
    industry: 'CleanTech SaaS',
    location: 'Boulder, CO, United States',
    revenue: 4300000,
    employees: 33,
    foundedYear: 2019,
    description: 'Commercial microgrid optimization and peak-shaving dispatch algorithms.',
    revenueGrowthPercent: 36,
    employeeGrowthPercent: 25,
    contact: {
      name: 'Soren Lind',
      title: 'CEO & Founder',
      email: 'soren@auraenergy.example.com',
      linkedin: 'https://linkedin.com/in/soren-lind-aura',
    },
  },
];
